Fix a FTBFS on i386-hurd
.
Imagemagick fail to build to build from source on i386-hurd
magick/utility.c: In function 'GetExecutionPath':
magick/utility.c:1022: error: 'cwd' undeclared (first use in this function)
magick/utility.c:1022: error: (Each undeclared identifier is reported only once
magick/utility.c:1022: error: for each function it appears in.)
make[2]: *** [magick/magick_libMagickCore_la-utility.lo] Error 1
.
The problem is due to a variable not renamed in a Hurd-specific block
of code in magick/utility.c.
The attached patch fixes the issue, fixing also a missing +1 in the
calculation of "extent".
Forwarded: http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=18831
Author: Pino Toscano <toscano.pino@tiscali.it>
Last-Update: 2011-05-27
Applied-Upstream: 6.7.0-2-Beta